### Variables
@baseUrl = http://localhost:8000

### Ping Test
GET {{baseUrl}}/ping
Content-Type: application/json

### read /microposts
GET {{baseUrl}}/microposts
Content-Type: application/json  

### Create /microposts
POST {{baseUrl}}/microposts
Content-Type: application/json  

{
    "title": "This is a test post"
}
