root = "."
tmp_dir = "tmp"

[build]
# Clear the screen on rebuild
cmd = "go build -o ./tmp/main ."
bin = "tmp/main"
# Gin in debug mode
full_bin = "APP_ENV=development GIN_MODE=debug ./tmp/main"
# Watch Go files
include_ext = ["go", "mod", "sum", "env"]
# Ignore these directories
exclude_dir = ["assets", "tmp", "vendor", "../frontend/node_modules", "docs"]
# Exclude test files
exclude_regex = ["_test\\.go"]
# Exclude unchanged files
exclude_unchanged = true
# Follow symlink for directories
follow_symlink = true
# Log file
log = "air.log"
# Stop on error
stop_on_error = true
# Send interrupt signal before killing process
send_interrupt = true
# Delay after sending interrupt signal
kill_delay = 500 # ms

[log]
time = true

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[screen]
clear_on_rebuild = true
keep_scroll = true